### ISSUE TITLE
integrate slack with heroku

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WWCodeManila-Hackathon-Site#7]
## Problem

* Manila team want to use https://manila.womenwhocode.com to connect their hackathon slack group for their hackathon app.
* They will be using Slack OAuth so hackaton participants won't need to sign up again to add their details about their devices and more.

## Solution
* CoreTeam to set up their env vars for that dyno.
* will unblock once keys are ready to be added 😉

**Comment by zassmin** [comment]
I think I took care of everything we needed. @kjcpaas or @michieriffic can you confirm?

**Comment by ogormans** [comment]
From Malia team on Nov 20th:

Please add the following keys to the Heroku app of Manila's hackathon website: `NODE_ENV=production`, `SESSION_SECRET` (any long string).

These are the keys that should be there:

```
FIREBASE_CLIENT_EMAIL=
FIREBASE_DATABASE_URL=
FIREBASE_PRIVATE_KEY=
FIREBASE_PROJECT_ID=
NODE_ENV=
SESSION_SECRET=
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=
SLACK_REDIRECT_URI=
```
Our hackathon is on Friday already so we need this added ASAP so we can test the app beforehand.

**Comment by kjcpaas** [comment]
@zassmin I sent you a message on Slack today (also a 311 form) about the additional keys we need. Have you added those as well? Thanks a lot for the help!

**Comment by kjcpaas** [comment]
Hi @zassmin we confirmed that the app is working as expected so the correct keys are in Heroku. Thanks a lot! 😸
